### ISSUE TITLE
Set the git commit dates to enforced-date, git author to the Prime Minister and git committer to the President

### ISSUE THREAD

**Issue by nzec** [prince-mishra/the-constitution-of-india#4]
Can be done using the `git commit --date=<date>`.

**Comment by dufferzafar** [comment]
@prince-mishra How are we planning to deal with dates before 1970? I think you mentioned `original date + 100 years` approach somewhere.

**Comment by prince-mishra** [comment]
@dufferzafar Yes, that is the simplest approach I could think of. 
I have done the same and pushed the changes already.
